### ISSUE TITLE
Finalize mail error tracking

### ISSUE THREAD

**Issue by svenhertle** [helfertool/helfertool#114]
We have three types of mails:

**Registration mails**
- [x]  Implement handler
- [x]  Show in web interface

**Mails sent for event**
- [x] Implement handler
- [x] Show in web interface (for sent mail)

**News**
- [x] Implement handler
- [x] Show in web interface (and allow to remove address directly)
